services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker_notifications:
    build: .
    command: celery -A config worker -Q notifications -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  worker_reports:
    build: .
    command: celery -A config worker -Q reports -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  worker_maintenance:
    build: .
    command: celery -A config worker -Q maintenance -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  flower:
    build: .
    command: celery -A config flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker_notifications
      - worker_reports
      - worker_maintenance
